%% Function Inlet
%% File: init.m

% Struct pliststep:
% 指定每个参数的遍历步长

% Struct plistrang:
% 指定每个参数的遍历范围，对每个参数，第一项为最小值，第二项为最大值

% Struct plistifergo
% 指定是否遍历某个变量，否者直接采用默认值plistDef

% Struct plistDef
% 默认值 

pliststep = struct( ...
    'drive_conversion_step', 0.1, ...
    'drive_fitness_step', 0.1, ...
    'release_rate_step', 0.01, ...
    'germline_resistance_forming_step', 0.1, ...
    'dd_mothertal_inheritance_step', 0.05, ...
    'log_immunity_speed_step', 0.1, ...
    'reducehtm_step', 0.1 ...
    );

plistrang = struct( ...
    'drive_conversion', [0.0,1.0], ...
    'drive_fitness', [0.1,1.0], ...
    'release_rate', [0.001,0.5], ...
    'germline_resistance_forming', [0,1], ...
    'dd_mothertal_inheritance', [0.0,0.5],...
    'log_immunity_speed', [-1,1],...
    'reducehtm',[0,1] ...
    );

plistifergo = struct( ...
    'drive_conversion', false, ...
    'drive_fitness', false, ...
    'release_rate', false, ...
    'germline_resistance_forming', false, ...
    'dd_mothertal_inheritance', false,...
    'log_immunity_speed', true,...
    'reducehtm', false ...
    );

results = cell(5);

cnt=1;
for field = fieldnames(plistifergo)'
    field = field{1};
    if field ~= "drive_conversion" && field ~= "drive_fitness"
        newlistif = plistifergo;
        newlistif.(field) = true;
        results{cnt} = main(pliststep, plistrang, newlistif);
        cnt=cnt+1;
    end
end

