% filename main.m
% Main function to init

plistlist = struct( ...
    'drive_conversion', {0.9, 0.9}, ...
    'drive_fitness', {0.9, 0.9}, ...
    'release_rate', {0.05, 0.06}, ...
    'germline_resistance_forming', {0.05, 0.05}, ...
    'dd_mothertal_inheritance', {0.05, 0.05}...
    );

parfor i = 1:length(plistlist)
    spacial(sprintf('Video/plot_%d.gif',i), plistlist(i));
end